baseurl = "https://www.sportsandvisualdata.com/"
languageCode = "en-us"
title = "Data analysis and visualization"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "App"
    url = "https://www.uv.es/vivigui/AppEuroACB.html"
[[menu.main]]
    name = "Software R"
    url = "https://CRAN.R-project.org/package=BAwiR"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/guivivi/sportsandvisualdata"
[[menu.main]]
    name = "Web"
    url = "https://www.uv.es/vivigui"

[params]
    description = "Website for visualization of sports and other industrial fields."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
